### ISSUE TITLE
Create 5029-GPA-page

### ISSUE THREAD

**Issue by Panadon-s** [konnerRG/EMOTIONAL_DAMAGE-re-#3]
Create new branch called '5028-GPA-page' from the 'development' branch. This is where the assignee must create a page to display their enrolled subjects, their grade and total GPA by using the select box function. The user can choose the year and semester.

(For the current semester, leave the grades and total GPA blank.)

-- name the title of the page with your name and surname.
-- The assignee can choose their preferred color for the navbar.

**Comment by konnerRG** [comment]
### Fix:
325086e - Added external script to GPA pages
