### ISSUE TITLE
Application Release:

### ISSUE THREAD

**Issue by konnerRG** [konnerRG/EMOTIONAL_DAMAGE-re-#9]
Deploy website and README.md file to the Git hub.
README file must consist of:
- The group name
- Name of members and details
- An application description and the how to use it
- Screenshot of the webpage (optional)
- The webpage URL.

**Comment by Panadon-s** [comment]
### Design:

![image](https://user-images.githubusercontent.com/77398559/149654784-79b5a7da-4d5b-4a01-8de6-4420685946bb.png)

**Comment by Panadon-s** [comment]
### Dev: 

Create README.md  7551104ddf10f2bfa9ca4ca50e459d52b72ad824
